---
global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
- job_name: haproxy_exporter
  consul_sd_configs:
  - server: '10.5.0.20:8500'
    services: ['haproxy-exporter']

- job_name: consul
  metrics_path: /v1/agent/metrics
  params:
    format: ['prometheus']
  static_configs:
  - targets: ['10.5.0.20:8500']

- job_name: nomad
  metrics_path: /v1/metrics
  params:
    format: ['prometheus']
  static_configs:
  - targets: ['10.0.5.10:4646']